interledger/rfcs

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
Fixes https://github.com/interledger/rfcs/issues/13 and https://github.com/interledger/rfcs/issues/14, thanks diminator
> p -> ledgerPlugin, fix store api inconsistency

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
resolves https://github.com/interledger/rfcs/issues/18
> Change 'incoming' event to 'receive'

- 0003-interledger-protocol/0003-interledger-protocol.md
- 0005-optimistic-transport-protocol/0005-optimistic-transport-protocol.md
- 0006-universal-transport-protocol/0006-universal-transport-protocol.md
- 0007-atomic-transport-protocol/0007-atomic-transport-protocol.md
See https://github.com/interledger/rfcs/issues/28
> Merge Optimistic and Universal modes into ILP

- 0011-interactive-transport-protocol/0011-interactive-transport-protocol.md
proposed in https://github.com/interledger/rfcs/issues/43
> Add Interactive Transport Protocol spec

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
From conversations with @justmoon . Clarifies when errors should be thrown, which methods require connection prior to their invocation, adds a `"ledger"` field to transfers so that the connector doesn't have to add it, and fixes conflicting information regarding `getInfo()`.
> Docs: clarify LedgerPlugin interface

- 0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md
changed to link to 0003-Interledger-Protocol instead
> remove outdated mention of UTP

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
As per RFCs issue [https://github.com/interledger/rfcs/issues/45#issuecomment-234931360](https://github.com/interledger/rfcs/issues/45#issuecomment-234931360)
> Update events in LedgerPlugin interface

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
Updates the ledger plugin interface spec with various changes that have been discussed in the issues.
> RFC-4: ILP addresses, remove cancellationCondition, add rejectIncomingTransfer

- 0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md
based on comments from @vhpoet on https://github.com/interledger/rfcs/pull/75#discussion-diff-75408084
> Fix old mentions of ITP in SPSP

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
Resolves https://github.com/interledger/rfcs/issues/93 . Documents the different error types and their purposes, as well as which functions return them.
> Feat: Add error types

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
Include a list of recommended connectors on `LedgerInfo`.
See: https://github.com/interledger/rfcs/issues/95 and https://github.com/interledger/js-ilp-plugin-bells/pull/40
> RFC-4: LedgerPlugin#getInfo includes "connectors"

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
- 0008-interledger-quoting-protocol/0008-interledger-quoting-protocol.md
* Add `plugin.sendMessage(message)` and `plugin.on("incoming_message")`.
* Update ILQP to use messaging instead of HTTP.
* Rename `plugin.send` to `plugin.sendTransfer`.
Fixes #96
> docs(004,008): add messaging; s/send/sendTransfer

- 0002-crypto-conditions/0002-crypto-conditions.md
> Fix column name in appendix

- 0002-crypto-conditions/0002-crypto-conditions.md
Removes ambiguity around endianness of bitmask
Fixes #71
> RFC-2:Change FeatureSuite type to unsigned int

- 0002-crypto-conditions/0002-crypto-conditions.md
Implementations MUST ignore message during validation
Fixes #39
Remove reference to OP_HASH256
Fixes #108
> Updates to PREIMAGE-SHA-256 description

- 0002-crypto-conditions/0002-crypto-conditions.md
- 0002-crypto-conditions/generated.html
- 0002-crypto-conditions/generated.xml
Regenerated XML and html files
Added ahopebailie as editor
> Regenerated draft-01

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
Related to https://github.com/interledgerjs/ilp-plugin-bells/pull/74
cc: @emschwartz
> docs(0004): add connect() options.timeout

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
Fixes https://github.com/interledger/rfcs/issues/141
> docs(0004): make plugin.get{Prefix,Account,Info} synchronous

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
Related to https://github.com/interledger/rfcs/issues/150
> feat: add RejectionMessage to LedgerPlugin

- 0016-pre-shared-key/0016-pre-shared-key.md
Starting write-up for PSK details format, similar to the HTTP request format. From @emschwartz and @stefan
> Docs: add PSK details spec

- 0011-interledger-payment-request/0011-interledger-payment-request.md
depends on https://github.com/interledger/rfcs/pull/166, https://github.com/interledger/rfcs/pull/175
* change the IPR format to only include a packet and condition
* replace JSON format with binary
* recommend using a PSK implementation to generate the payment request
resolves https://github.com/interledger/rfcs/issues/138
> RFC 11: Change IPR to use ILP Packet and PSK

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
resolves https://github.com/interledger/rfcs/issues/47
> Clarify that plugin interface is Javascript-specific

- asn1/InterledgerPaymentRequest.asn
- asn1/InterledgerProtocol.asn
- asn1/InterledgerQuotingProtocol.asn
This is just a first attempt. LMK your feedback.
Not sure about the additional data in the errors. Rather than having a content type, I was thinking of just making it JSON by convention. I don't think computers should ever really look at this field. They should only use the code. The `data` is really just for human developers. So making it an UTF8String and using JSON by convention seems perfectly fine.
> ASN.1: ILP Errors and IPR

- 0001-interledger-architecture/0001-interledger-architecture.md
- 0003-interledger-protocol/0003-interledger-protocol.md
resolves https://github.com/interledger/rfcs/issues/150
related to https://github.com/interledger/rfcs/pull/175
> Add errors to Interledger Protocol spec

- 0016-pre-shared-key/0016-pre-shared-key.md
Closes https://github.com/interledger/rfcs/issues/187 .
> Docs: specify size of auth tag and encryption padding in PSK

- 0010-connector-to-connector-protocol/0010-connector-to-connector-protocol.md
Companion to https://github.com/interledgerjs/ilp-routing/pull/40
> C2C and ILQP to integers

- 0020-explain-like-im-five/0020-explain-like-im-five.md
Replaces https://github.com/interledger/rfcs/pull/193
@professorhantzen I squashed your PR into one commit and gave it the RFC number 20. If this looks good to you we can merge this in
> docs(0020): add Interledger: Explain Like I'm Five (ELI5)

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
- 0010-connector-to-connector-protocol/0010-connector-to-connector-protocol.md
Companion to https://github.com/interledgerjs/ilp-connector/pull/337
> feat: add optional plugin.getInfo().{min,max}Balance

- 0008-interledger-quoting-protocol/0008-interledger-quoting-protocol.md
- asn1/InterledgerQuotingProtocol.asn
Depends on https://github.com/interledger/rfcs/pull/198
> docs(0008): ILQP binary messages

- 0008-interledger-quoting-protocol/0008-interledger-quoting-protocol.md
This PR intends to fix https://github.com/interledger/rfcs/issues/225
> docs(0008): final/destination != next/outgoing

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
- asn1/GenericPacket.asn
> Merge #198

- 0021-plugin-rpc-api/0021-plugin-rpc-api.md
With several RPC based plugins, this API should be standardized. It can also be used for the asymmetric trust-line plugins.
> Docs: add plugin virtual RPC API

- scripts/generate_web.js
- tmpl/rfc.ejs.html
Show draft number
Add link to latest draft
> Tweak RFCs template

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
When viewing on our website,
* https://interledger.org/rfcs/0004-ledger-plugin-interface/#messageto works
* https://interledger.org/rfcs/0004-ledger-plugin-interface/#message-to doesn't
Likewise when viewing on github,
* https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#messageto works
* https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#message-to doesn't
> docs(0004): fix field links

- asn1/CommonLedgerProtocol.asn
- asn1/GenericPacket.asn
- asn1/InterledgerPaymentRequest.asn
- asn1/InterledgerQuotingProtocol.asn
After long debate, I can now see the logic in this as a protocol that talks
through the ledger, to the connector.
Just a few minor adjustments:
1) merge CustomResponse into Ack, they serve the same function of responding to
a request without including a packet.
2) add some code comments
> CLP comments

- asn1/InterledgerPacket.asn
- asn1/InterledgerPaymentRequest.asn
- asn1/InterledgerQuotingProtocol.asn
* require packet in IPR to be an InterledgerPacket, not just any octet string
* rename the GenericPacket.asn file to InterledgerPacket.asn, to match the class it defines
* ~~fix incorrect module name in InterledgerPaymentRequest.asn~~
* fix newlines ~~and punctuation~~ in a few places
> fix: asn1 corrections

- asn1/InterledgerPacket.asn
- asn1/InterledgerPaymentRequest.asn
- asn1/InterledgerQuotingProtocol.asn
- circle.yml
- scripts/check-asn.sh
- scripts/generate_web.js
- tmpl/rfc.ejs.html
Fixes https://github.com/interledger/rfcs/issues/216
> chore: check ASN syntax in CI; generate ASN docs

- asn1/CommonLedgerProtocol.asn
> feat: puts protocolData inside of a sequence

- 0023-bilateral-transfer-protocol/0023-bilateral-transfer-protocol.md
@justmoon's notes, copied from https://ripplelabs.slack.com/files/U024N53C7/F74RUKDLK/notes.md: 
- BTP URIs: btp+wss://:token@hostname.example:port/path
- There is only one BTP version, but in the future we will likely add a subprotocol to the auth message that allows the client to advertise features and a subprotocol for the response that allows the server to acknowledge these features
- Subprotocols either use the feature 
- The first protocol in the packet is called the primary
- If the packet contains more than one protocol with the same name, reject the whole packet with a BTP error
- If there are zero elements in protocol data, this is syntactically valid, although in the case of Message may return a BTP error
- Nginx proxy statement for each peer
- Plugins listen with unencrypted …
> Apply changes from last night's meeting

- 0003-interledger-protocol/0003-interledger-protocol.md
- asn1/InterledgerProtocol.asn
> docs(0003): add fulfillment data ilp packet

- 0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
> docs(0004): add fulfillment data to lpi

- 0022-hashed-timelock-agreements/0022-hashed-timelock-agreements.md
> fix: mention that the preimage may be known to Alice

- 0024-ledger-plugin-interface-2/0024-ledger-plugin-interface-2.md
> sendMoney returns `undefined`

- 0015-ilp-addresses/0015-ilp-addresses.md
- Remove concept of "Address Prefixes"
- Remove reference to ledgers in addressing
- Remove concept of local vs forwarding behaviour at connectors
Fixes #422 
Fixes #410
> FIX: Changes to reflect ILPv4 model

- .github/stale.yml
https://probot.github.io/apps/stale/
> Add Stale app to automatically close old issues

- 0000-node-requirements/0000-node-requirements.md
Added statements of accounts. If you are uncomfortable of some expressions, please modify as you think because my English is not so good.
> Added statements of accounts

- 0029-stream/0029-stream.md
See: https://github.com/interledgerjs/ilp-protocol-stream/pull/69
> doc(0029): expose asset details in stream

- CONTRIBUTING.md
- LICENSE
> Add CC-BY-SA 4.0 license

- .gitignore
- 0030-notes-on-oer-encoding/0030-notes-on-oer-encoding.md
> Update OER Encoding of Dates

- 0035-ilp-over-http/0035-ilp-over-http.md
resolves https://github.com/interledger/rfcs/issues/517
> Clarify host header

- 0030-notes-on-oer-encoding/0030-notes-on-oer-encoding.md
Fixes based on report from Bruno Konik
https://mailarchive.ietf.org/arch/msg/ledger/qYGs_S_Yk8xuVMI3GwTrHlEd7uc
> Fix negative integer examples

- 0000-ilp-ping-protocol/0000-ilp-ping-protocol.md
- 0000-ilp-ping-protocol/images/bidirectional-flow.svg
- 0000-ilp-ping-protocol/images/unidirectional-flow.svg
Add images and some minor fixes.
Signed-off-by: Taiga Nakayama <dora@dora-gt.jp>
> Add images for the unidirectional-flow and bidirectional-flow.

- 0027-interledger-protocol-4/0027-interledger-protocol-4.md
> Remove reference to PSK2

- 0028-web-monetization/0028-web-monetization.md
- tmpl/rfc.ejs.html
Update template to accept absolute URLs for deprecated specs
> Update template and deprecate IL-RFC 28

- tmpl/rfc.ejs.html
Corresponding PR: https://github.com/interledger/interledger.github.io/pull/128
> Update nav template to match interledger.org update

- 0023-bilateral-transfer-protocol/0023-bilateral-transfer-protocol.md
This PR serves the same purpose as https://github.com/interledger/rfcs/pull/548: to simply rebuild the templates and deploy the changes made in https://github.com/interledger/rfcs/pull/552 by adding the magic string `Skip Version Check` in the commit message.
> Rebuild templates - Skip Version Check

- 0038-settlement-engines/0038-settlement-engines.md
> Fix typo in Engines spec

- 0001-interledger-architecture/0001-interledger-architecture.md
- 0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md
- 0014-paid-http-apis/0014-paid-http-apis.md
- 0015-ilp-addresses/0015-ilp-addresses.md
- 0018-connector-risk-mitigations/0018-connector-risk-mitigations.md
- 0019-glossary/0019-glossary.md
- 0022-hashed-timelock-agreements/0022-hashed-timelock-agreements.md
- 0023-bilateral-transfer-protocol/0023-bilateral-transfer-protocol.md
- 0027-interledger-protocol-4/0027-interledger-protocol-4.md
- 0029-stream/0029-stream.md
- 0030-notes-on-oer-encoding/0030-notes-on-oer-encoding.md
- 0031-dynamic-configuration-protocol/0031-dynamic-configuration-protocol.md
- 0032-peering-clearing-settlement/0032-peering-clearing-settlement.md
- 0033-relationship-between-protocols/0033-relationship-between-protocols.md
- 0034-connector-requirements/0034-connector-requirements.md
- 0035-ilp-over-http/0035-ilp-over-http.md
- 0036-spsp-pull-payments/0036-spsp-pull-payments.md
- 0037-spsp-invoices/0037-spsp-invoices.md
- 0038-settlement-engines/0038-settlement-engines.md
> Add proper “type” to all RFCs

- README.md
> Skip Version Check
