0001-interledger-architecture/0001-interledger-architecture.md
0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md

This moves the renamed Simple Payment Setup Protocol out of the architecture doc and into its own RFC (just a placeholder for now)

OWSP -> SPSP, and text edits

---

0002-crypto-conditions/0002-crypto-conditions.md
0002-crypto-conditions/README.md

Downsides:
- GitHub doesn't render the markdown nicely (neither does Dactyl right now)
- Some newer ITU references aren't in the xml2rfc database but the converter assumes they will be, causing errors. Renamed to "itu" as a workaround.
Upsides:
- Still pretty easy to write by hand
- Generated HTML has very few non-whitespace differences from the original generated HTML. 
- Fixed a couple typos while I was at it.

docs(0002): markdown version

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

this is important for senders and connectors in case they miss the notification of a fulfillment and need to retrieve it later

Add getFulfillment to Ledger Plugin Interface

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

`fulfillCondition` should no longer throw when fulfilling a fulfilled transfer, in order to remain idempotent. `AlreadyRolledBackError` should be emitted when someone tries to fulfill a cancelled transfer and also when `getFulfillment` is used to fetch a cancelled transfer. `AlreadyFulfilledError` is emitted when trying to reject a fulfilled transfer. `DuplicateIdError` is emitted when sending a transfer with a duplicate ID that does not otherwise match the existing transfer.

docs(004): add AlreadyRolledBackError, AlreadyFulfilledError, DuplicateIdError

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

I forgot to add `"connectors"` to the `getInfo()` example at the same time as [ConnectorInfo](https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#class-connectorinfo).

docs(0004): add "connectors" to getInfo example

---

0002-crypto-conditions/0002-crypto-conditions.md

Specify that we use SHA-256 and a salt length of 32 bytes
Fixes #104

Define RSASSA-PSS params

---

0008-interledger-quoting-protocol/0008-interledger-quoting-protocol.md

The example already shows them as strings, but the Type column showed the amount values in QuoteParameters as "Number" type. Corrected it to be String in both.

docs(0008): QuoteParameters amounts to string type

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

Add `NoSubscriptionsError` to `plugin.sendMessage`.
This is for https://github.com/interledgerjs/five-bells-ledger/issues/362:
> Instead, the ledger should give an error message that the connector could not be reached.

docs(0004): sendMessage NoSubscriptionsError

---

0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md

Add Cache Control header to the SPSP spec so the SPSP client doesn't have to continue to use a hardcoded 60 second cache.

SPSP caching

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

Change the ledger plugin API to use from/to fields instead of the
ambiguous `account` field.
To illustrate how the previous API was confusing: In plugin-bells, we
actually populated the `account` field for incoming transfers with the
sending account, while we populated the `account` field for incoming
messages with the receiving (`to`) account.
Providing both sending and receiving accounts for both transfers and
messages allows us to more closely mirror the underlying API and reduce
the potential for confusion.

RFC-4: Replace account with from/to

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

As stated in the Twelfth Networking Truth (RFC 1925): In protocol design, perfection has been reached not when there is nothing left to add, but when there is nothing left to take away.
Change the fulfillment format to a String (which matches what the reference implementation actually uses.)
Since we only support one condition type, an abstraction layer like crypto-conditions doesn't make sense in this API. Note that this RFC only applies to the JavaScript implementation, other implementors are welcome to choose a different API.

feat: switch to simple conditions

---

0015-ilp-addresses/0015-ilp-addresses.md

This PR consolidates information from #132 and #31, plus summarizes up-to-date thoughts from the team on addresses in general.
Summary:
- Intro to what addresses are for and high-level view of how they're used for routing
- Rules for what's a valid ILP Address, including lists of currently-defined prefixes
- Descriptions of different segments and what they might be used for
- Examples and recommendations for segments

ILP Addresses (RFC0015)

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

The `incoming_fulfill` event should emit a `fulfillment` `String`, not `Buffer`.
(see https://github.com/interledger/rfcs/pull/160)

fix: fix fulfillment typo

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

The following two functions are not the same, the spec should be specific about that:
```
function thrower() {
if (problem) {
throw new Error('oops');
}
return Promise.resolve('success');
}
function rejecter() {
if (problem) {
return Promise.reject(new Error('oops'));
}
return Promise.resolve('success');
}
```

Differentiate between throwing and rejecting

---

0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md

* use binary ILP packet format
* use PSK instead of IPR
* remove the payee/invoice distinction
* switch to integer amounts
* receiver info can be used to send multiple payments
* "receiver" now only refers to the entity receiving the payment, not the SPSP endpoint
* switch Webfinger rel to https://interledger.org/rel/spsp/v2
Depends on https://github.com/interledger/rfcs/pull/166
Resolves https://github.com/interledger/rfcs/issues/152

RFC-9: SPSPv2 (switch to PSK)

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md

Since we switched to integers on transfers and ledger balances, `scale` is always zero, so that's useless in ledgerInfo. However, `currencyScale` is needed now. At the same time, deprecated `currencySymbol` since symbols, like colors, and human languages are a UI thing and not a concern of the ledger plugin. IMHO, the plugin interface should only deal with machine-readable data, not with human-computer interface.

docs(0004,0009): Rename scale to currencyScale, deprecate currencySymbol, deprecate precision

---

scripts/generate_web.js

This will make links compatible with both github and Interledger website
Reading the docs from github should lead to the right content as well as reading it from the website, without changing from one another.
It changes all `../xxxx-<anything>/xxxx-<anything>.md` to `../xxxx-<anything>`

Fixes relative links across all rfcs's.

---

0019-glossary/0019-glossary.md

It’s minor, but some of the headings in the [glossary](https://github.com/interledger/rfcs/blob/master/0019-glossary/0019-glossary.md) are bigger than the others (they have only a single #-sign, but should have two pound-signs.  This fixes that.

Fix Heading Styles

---

0015-ilp-addresses/0015-ilp-addresses.md

Since [GitHub changed their parser][1], [pipe characters in tables must now be escaped][2] even if they are part of inline code items. Since some other parsers don't work this way, the best way to solve this is to avoid using the regular expression in a table. Since the regexes for recognizing addresses are rather long anyway, taking them out of the table also reduces the chances they overflow off the side of the screen/column.
[1]: https://githubengineering.com/a-formal-spec-for-github-markdown/
[2]: https://github.github.com/gfm/#tables-extension-

Remove regexes from table for MD compatibility

---

0021-plugin-rpc-api/0021-plugin-rpc-api.md

You could say that it's enough to define one example of the 'send_request' method, but in the interest of giving the reader what they need when they get to this doc, since we have two request types, I propose to give an example of each one.

Add example of route broadcast

---

0003-interledger-protocol/0003-interledger-protocol.md

It's not enough for the sender to negotiate the address, an amount, and a cryptographic condition with the destination.
In HTLAs, the condition is never absolute, it's always tied to a timeout, as well.

fix: clarify role of timeout

---

0003-interledger-protocol/0003-interledger-protocol.md
0008-interledger-quoting-protocol/0008-interledger-quoting-protocol.md
asn1/InterledgerTypes.asn

Hi,
Referring to  #230, and some discussion in #249, the various specs should explicitly mandate the time format and timezone to be used - in a nutshell, the OER GeneralizedTime type is too general and could be misused. Mandating a common time format and timezone should remove some of the potential problems.

feat: fix a time format and zone for Interledger Timestamp

---

asn1/GenericPacket.asn

* [InterledgerProtocolPayment](https://github.com/interledger/rfcs/blob/master/asn1/GenericPacket.asn#L30) is what can be wrapped inside an ILP packet
* [InterledgerProtocolPayment](https://github.com/interledger/rfcs/blob/master/asn1/InterledgerProtocol.asn#L15) is also what has been defined.
* Yet [InterledgerProtocolPaymentMessage](https://github.com/interledger/rfcs/blob/master/asn1/GenericPacket.asn#L11) is what the GenericPacket doc tries to include from the InterledgerProtocol doc.

fix: include the correct class name

---

asn1/CommonLedgerProtocol.asn
asn1/InterledgerPaymentRequest.asn

Same change for CustomRequest, as already merged for Ack.
Since the typeId is already in the CLPP, you can go straight to the CustomRequest's only data field.

fix: align CustomRequest with Ack

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

Related to https://github.com/interledgerjs/ilp-connector/pull/390
`NotAcceptedError` is too general for the connector to accurately generate a `T04: Insufficient Liquidity` ILP error.

docs(0004): add plugin InsufficientBalanceError

---

asn1/CommonLedgerProtocol.asn

This PR aims to find a compromise between all our different views. It differs from #263 in that it does not allow for `requestId=0`, it distinguishes `Response` from `ErrorResponse` in the CallSet, and it leaves CallSet id's reserved for non-ILP Prepare/Fulfill/Reject.
With these minor changes, CLP still has only one native protocol, namely Interledger. All other protocols have to use SideProtocolData. However, the CallSet could easily be extended with other native protocols. Additionally, it could easily be extended with conditionally paid custom requests, as well as unconditional ones.
As Ben and I discussed this afternoon, it may be a useful compromise not to define these currently unused features yet, but to accommodate for possibly adding them in the future.

docs: introduce CommonLedgerProtocol

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

* mention optionality of `transfer.noteToSelf`, `transfer.custom`, and `message.custom` in their descriptions
* mention that `message.ilp` is optional in messages (we don't include `message.ilp` when sending route broadcasts, for example)
* leave `transfer.ilp` as a required field

fix: clarify changes from #304

---

0003-interledger-protocol/0003-interledger-protocol.md
0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
0008-interledger-quoting-protocol/0008-interledger-quoting-protocol.md
0011-interledger-payment-request/0011-interledger-payment-request.md
0016-pre-shared-key/0016-pre-shared-key.md
asn1/InterledgerPacket.asn
asn1/InterledgerProtocol.asn
asn1/InterledgerQuotingProtocol.asn

I tried to push the abbreviation 'ipp' but it didn't really seem to stick.
In any case, the current situation where 'ILP Packet' can be either https://github.com/interledger/rfcs/blob/master/asn1/InterledgerProtocol.asn#L15 by itself, or wrapped inside https://github.com/interledger/rfcs/blob/master/asn1/GenericPacket.asn#L40 is way too confusing, and is more or less guaranteed to lead to bugs where people try to parse it with/without the wrapper when the opposite was intended.

fix: ILP Packet -> InterledgerProtocolPayment

---

0016-pre-shared-key/0016-pre-shared-key.md

This fixes #335. Changes:
* instead of encrypting directly with the `shared_secret`, take the HMAC of the string `'ilp_psk_encryption'` first.
* instead of generating the fulfillment directly with the `shared_secret`, take the HMAC of the string `'ilp_psk_condition'` first.
These are breaking changes, but since there is only one implementation of PSK so far (namely, [ilp-kit](https://github.com/interledgerjs/ilp-kit), which uses the [ilp module](https://www.npmjs.com/package/ilp) for both [encryption](https://github.com/interledgerjs/ilp/blob/master/src/utils/crypto.js#L55) and [fulfillment generation](https://github.com/interledgerjs/ilp/blob/master/src/utils/crypto.js#L48)), I think it's easier for everyone if we leave the version string as `'PSK/1.0'`.
Other alternatives would be to …

fix: breaking change to PSK spec, to match what ilp-kit does

---

0003-interledger-protocol/0003-interledger-protocol.md
asn1/InterledgerPacket.asn
asn1/InterledgerProtocol.asn

Counter-proposal against https://github.com/interledger/rfcs/issues/312#issuecomment-339492419

feat: introduce best-effort payments (with no amount specified)

---

0004-ledger-plugin-interface/0004-ledger-plugin-interface.md
scripts/generate_web.js
tmpl/rfc.ejs.html

Update web scripts and template for deprecated specs
@bsteinlo I have updated the spec template to insert a new `<p class="deprecated">...</p>` tag at the top of the page if the spec is deprecated. Right now it has no CSS defined for `.deprecated` but the plan will be to make it banner or similar eye-catching element.
Is this HTML okay to work with?

Deprecate RFC 4

---

0015-ilp-addresses/0015-ilp-addresses.md

The address spec is missing the `local` allocation scheme as defined in the following [table](https://github.com/interledger/rfcs/blob/master/0015-ilp-addresses/0015-ilp-addresses.md#allocation-schemes).

add missing local address scheme to ABNF spec and regex

---

0001-interledger-architecture/0001-interledger-architecture.md

Fixed some typos, changed hyperlinks (used to point to deprecated protocols like LPIv1), and added STREAM in the transport section.

docs: rfc 0001 update

---

0027-interledger-protocol-4/0027-interledger-protocol-4.md

Clarify the `executionCondition` field in the ILP Prepare packet, so it's explicit that the condition does not change across all hops of a payment chain.

Clarify that the executionCondition doesn't change

---

0015-ilp-addresses/0015-ilp-addresses.md

- Reword the "routing" section to be slightly more approachable
- fix spelling of Ethereum

Minor touch-ups to ILP Addresses spec

---

.circleci/config.yml

Fix for missing `.ssh` dir when getting Github SSH keys

Update CircleCI config.yml

---

CONTRIBUTING.md

Small typo in contribution guidelines. Corrected here.

Fix a typo in contribution guidelines

---

0029-stream/0029-stream.md

Allow STREAM implementations to support `VarUInt`s with a maximum size (UInt64) for performance reasons.
See: https://github.com/interledgerjs/ilp-protocol-stream/pull/102.

docs(0029): impl note for VarUint max size

---

0018-connector-risk-mitigations/0018-connector-risk-mitigations.md

At worst, a connector can withhold a payment to its counterparty in
the fulfill phase but get paid by another connector. This change adds some details related to this.

Add connector risk information

---

0028-web-monetization/0028-web-monetization.md

Update meta tag to not include the / so that it follows the HTML5 syntax for meta tags. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

docs(0028) update meta tag to follow html5 syntax

---

0035-ilp-over-http/0035-ilp-over-http.md

Here is a minimal spec for the protocol proposed in [this blog post](https://medium.com/interledger-blog/thoughts-on-scaling-interledger-connectors-7e3cad0dab7f).

Add ILP Over HTTP

---

0026-payment-pointers/0026-payment-pointers.md

Just reporting these while trying to eat the docs :) I did notice some inconsistent use of http/HTTP that I wasn't sure was meaningful, if anyone cares to include relevant changes in this `draft:` bump.

docs(0026): fix typo

---

0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md

As promised when closing #501, this is the reduction of the SPSP spec to its basics. It describes the purpose of SPSP, the minimal response of an endpoint query and how to use it to set up a STREAM connection. It also briefly explains how to use this connection to make a simple push payment and data transfer. It references other specs for anything more specific, e.g. invoices and pull payments.

Basic SPSP spec

---

0019-glossary/0019-glossary.md

The RFC *0017-ledger-requirements* is deprecated.
> Since ILPv4 the protocol has placed no specific requirements on underlying settlement ledgers.

Remove dead link & ledger layer requirements

---

0036-spsp-pull-payments/0036-spsp-pull-payments.md

As promised when closing #501, this is the stand-alone pull-payment spec. It extends the basic SPSP spec by explaining how a pull payment is conducted once a STREAM connection has been established using SPSP. It also specs out optional response body fields.

Pull payment spec

---

0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md

This updates the link to the invoice spec now it has been merged.

docs(0009): fix link to invoice spec

---

.editorconfig
0028-web-monetization/0028-web-monetization.md

Overview
* Specify observing head for monetization tags
* Introduce concept of a meta "Tags Set"
* if tags are injected they must be ordered carefully to work with meta observer
* Rename Request-ID to Monetization-ID
* leave `requestId` field the same for the moment
* Add comment near field for correlation
* Consistently use `browser` rather than mix of `browser` and `agent`
* Bar iframe support until have a sensible working implementation
* meta[content] can specify a payment pointer or an SPSP url
* Generically referred to as `Payment Setup Endpoint`
* Make it clear that the amount is the destination received amount

docs(0028): update spec with monetization tag observation changes

---

0027-interledger-protocol-4/0027-interledger-protocol-4.md

Fixes #537 by clarifying the description of an `F04` rejection reason.

Update F04 definition per #537

---

README.md

#547 didn't get deployed via CircleCI because it didn't have the magic words "Skip Version Check" in the commit message. (It changed the templates, but not the substance of the drafts, but got flagged for changing drafts without updating their version numbers.)

Rebuild templates - Skip Version Check

---

0029-stream/0029-stream.md

Fixes #546 by clarifying the STREAM RFC.
* Clarify that `ConnectionAssetDetails` MUST not change during the lifetime of a Connection.

Fixes #546

---

0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md

It's an unwritten rule right now that SPSP servers include CORS headers to allow Web Monetization polyfills to function.
All ILP enabled wallets currently support this behavior already, but including it here will make it easier for future ILP enabled wallets to follow this recommendation.

docs(0009): recommend cors headers for spsp

---

0035-ilp-over-http/0035-ilp-over-http.md

ILP-over-HTTP has a known issue that if the response containing a Fulfill packet is dropped (e.g. due to a network error), there's no mechanism to retry it, so the balances between the two peers will get out of sync and require manual reconciliation. Also, if the request with an ILP Prepare is dropped, it won't be rejected until the packet expires, which is undesirable since payments may take longer.
This proposes a backwards compatible change to ILP-over-HTTP to separate the Prepare and Fulfill/Reject into two separate HTTP request/responses. Each packet has a corresponding idempotency key enabling clients to safely retry packets without triggering the same side effect multiple times.
The flow looks roughly like:
1. Alice sends `POST` with the ILP Prepare to Bob.
1. Bob begins processing …

Add idempotence/retry behavior to ILP-over-HTTP

---

0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md
0023-bilateral-transfer-protocol/0023-bilateral-transfer-protocol.md
0029-stream/0029-stream.md
0032-peering-clearing-settlement/0032-peering-clearing-settlement.md
0035-ilp-over-http/0035-ilp-over-http.md
0038-settlement-engines/0038-settlement-engines.md
0039-stream-receipts/0039-stream-receipts.md

We still have some leftover broken links after the website migration and spec deprecation exercise. Hopefully this catches all of them, if not, more PRs to come.

chore: fix broken links on specs

---

0015-ilp-addresses/0015-ilp-addresses.md

This fixes the ILDCP link on the "ILP Addresses" RFC.

Fix ILDCP link in IL-RFC-0015
